CREATE TABLE `house` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目名称',
  `developer` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '开发商',
  `equity` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '产权 如永久产权',
  `houseType` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '类型 如公寓',
  `houseTagIds` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '房屋标签id',
  `decorate` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '装修 如精装修',
  `handingTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '交房时间',
  `loans` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '贷款 如可贷款',
  `incisePay` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '分期 可分期',
  `houseState` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '房屋状态 期房在售',
  `info` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目简介',
  `htmlInfo` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '项目描述 富文本',
  `minPrice` int(11) NOT NULL COMMENT '项目价格范围左边界',
  `maxPrice` int(11) NOT NULL COMMENT '项目价格范围右边界',
  `increasePercent` int(11) NOT NULL COMMENT '近一年涨幅 百分比',
  `countryId` int(11) NOT NULL COMMENT '国家id',
  `countryStr` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `provinceId` int(11) NOT NULL COMMENT '省id 国外对应州id',
  `provinceStr` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `firstpayPercent` int(11) NOT NULL COMMENT '首付比例',
  `rentPercent` int(11) NOT NULL COMMENT '年均租金 百分比',
  `createTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `putawayTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '上架时间',
  `updateTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `operateId` int(10) unsigned zerofill NOT NULL COMMENT '操作人用户id',
  `state` int(11) NOT NULL DEFAULT '0' COMMENT '楼盘状态 0未上架 1已上架  2已下架 3已删除',
  `stick` int(11) NOT NULL DEFAULT '0' COMMENT '0 取消推荐  1推荐',
  `shareTitle` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '分享标题',
  `shareContent` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '分享内容',
  `shareImg` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '分享图片',
  `isGreenCard` int(11) NOT NULL DEFAULT '0' COMMENT '0 不可办  1可办',
  `greenCardUrl` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '' COMMENT '绿卡详细介绍url',
  PRIMARY KEY (`id`),
  KEY `operate_id` (`operateId`)
) ENGINE=InnoDB AUTO_INCREMENT=132 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;